### ISSUE TITLE
DPL-002 BUG - comment duplication in pipeline inboxes [C=M V=2]

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3166] opened 2021-04-22 15:17 UTC
The displayed comments are showing duplicates, at times this slows down the pipeline inbox users as they have to read all the displayed comments.
Example in RT ticket
https://rt.sanger.ac.uk/Ticket/Display.html?id=717970

Primary contacts
Lynda D
Tris

Looking at the NovaSeq inbox http://sequencescape.psd.sanger.ac.uk/pipelines/51
The comments displayed are mapped to request but also include labware comments.

Perhaps just apply uniq to the comment descriptions?

**Comment by JamesGlover** [comment] 2021-05-06 12:40
The problem is that there *are* multiple identical comments. If we do a uniq on them, then we have to also do that when fetching the counts, which will impact on inbox speed. Also, its then unclear what we should show when a person clicks through, as:

1) Comments link to the thing they are associated with, do we just display one of them, or have the comment counts differ when you click through?
2) What happens if you try to delete one of these comments, how do we know which one to delete? 

More details in existing issue:
https://github.com/sanger/sequencescape/issues/3107

**Comment by stevieing** [comment] 2022-01-27 14:40
Duplicate of #3107

**Closed by stevieing** 2022-01-27 14:40 UTC
Labels: bug
