### ISSUE TITLE
DPL-088 [BUG] Editing of batches to swap lane position [C=M, V=5]

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3253] opened 2021-07-15 15:50 UTC
If a pool has been assigned to a lane in the wrong order edit batch has a facility where the pool can be swapped with another to position it correctly. 
However this is inconsistent in it's success and fails to update the MLWH. 
It also fails to work if the pools are not next to each other (2 moves).

**Comment by JamesGlover** [comment] 2022-01-04 12:18
A large part of this problem comes from the fact that batch editing is handled by a series of AJAX requests, which can get resolved by different servers in odd orders. I think there may be something else going on too, as we also sometimes end up with odd inconsistent database states.

Last time I looked at the code, that batch update appeared to be wrapped in a transaction, and I couldn't work out how we were ending up with some of these states. However, on summarising now it occurs to me that I'm not sure I confirmed the payload coming from the front end. It may be that we're ending up sending invalid payloads.

A simple solution will be to remove the AJAXiness, and simple provide a save button instead. Might be worth taking a refactor pass to the code as well, as its probably quite dated.

**Comment by JamesGlover** [comment] 2022-01-04 12:20
Lack of WH updates may be a timestamp issue, as we're possibly only updating the batch requests. Its probably worth double checking this is still a problem though, as a few broadcast bugs have been fixed since this ticket was submitted.

**Comment by neilsycamore** [comment] 2022-01-18 10:44
Created batch 70511.
When I follow the link to 'Swap lanes editing' I get a routing exception....

An ActionView::Template::Error occurred in batches#filtered:

  No route matches {:action=>"all", :controller=>"batches", :id=>"70511"}
  lib/informatics/views/platform/_item.html.erb:4


-------------------------------
Request:
-------------------------------

  * URL        : http://uat.sequencescape.psd.sanger.ac.uk/batches/70511/filtered
  * HTTP Method: GET
  * IP address : 172.27.19.86
  * Parameters : {"controller"=>"batches", "action"=>"filtered", "id"=>"70511"}
  * Timestamp  : 2022-01-18 10:30:32 +0000
  * Server : sss1-uat
    * Rails root : /var/www/sequencescape/releases/20220117103522
  * Process: 30834

**Comment by KatyTaylor** [comment] 2022-01-19 11:26
Put this back into 'to do' due to above comment and also because it's caused pagination to appear on tables that didn't have it previously.

original pr - https://github.com/sanger/sequencescape/pull/3483
reverted pr - https://github.com/sanger/sequencescape/pull/3500

**Closed** 2022-01-20 16:32 UTC
Labels: bug
